on: push

name: Integration Tests
jobs:
  lint_test:
    name: ${{ matrix.python_version }} lint test
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python_version: ["3.6", "3.7", "3.8"]        
    steps:
      - name: Set up python ${{ matrix.python_version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python_version }}
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Build featuretools package
        run: make package_featuretools
      - name: Install featuretools with optional, dev, and test requirements
        run: |
          pip config --site set global.progress_bar off
          python -m pip install --upgrade pip
          python -m pip install -e unpacked_sdist/[koalas]
          python -m pip install -r unpacked_sdist/dev-requirements.txt
          python -m pip install -r unpacked_sdist/test-requirements.txt
      - name: Run lint test
        run: make lint

  unit_tests:
    name: ${{ matrix.python_version }} unit tests ${{ matrix.optional_libraries }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python_version: ["3.6", "3.7", "3.8"]
        optional_libraries: ["minimal", "optional"]
    steps:
      - name: Set up python ${{ matrix.python_version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python_version }}
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Build featuretools package
        run: make package_featuretools
      - name: Set up pip and graphviz
        run: |
          pip config --site set global.progress_bar off
          python -m pip install --upgrade pip
          sudo apt update && sudo apt install -y graphviz
      - if: ${{ matrix.optional_libraries == 'optional' }}
        name: Install featuretools with optional requirements and test requirements
        run: |
          sudo apt install -y openjdk-11-jre-headless
          JAVA_HOME="/usr/lib/jvm/java-11-openjdk-amd64"
          python -m pip install -e unpacked_sdist/[koalas]
          python -m pip install -r unpacked_sdist/test-requirements.txt
      - if: ${{ matrix.optional_libraries != 'optional' }}
        name: Install featuretools with test requirements (no optional requirements)
        run: |
          python -m pip install -e unpacked_sdist/
          python -m pip install -r unpacked_sdist/test-requirements.txt
      - if: ${{ matrix.python_version == 3.6 && matrix.optional_libraries == 'optional' }}
        name: Run unit tests with code coverage
        run: |
          python -m pip install "$(cat dev-requirements.txt | grep codecov)"
          coverage erase
          cd unpacked_sdist/
          coverage erase
          pytest featuretools/ -n 2 --cov=featuretools --cov-config=../.coveragerc
          cd ../
          cp unpacked_sdist/.coverage .coverage
          codecov --required
      - if: ${{ matrix.python_version != 3.6 && matrix.optional_libraries != 'optional' }}
        name: Run unit tests (no code coverage)
        run: |
          source venv/bin/activate
          cd unpacked_sdist
          pytest featuretools/ -n 2
